spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        follower: follower_channel
        achievement: achievement_channel

  messages:
    basename: messages

server:
  port: 8083

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
user-service:
  host: localhost
  port: 8080

telegram-bot:
  name: "CorpXtestBot"
  token: "6606365809:AAEmjWeXZ4UfZdr6ETACVxVTGoTPTvERNoc"